// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZW3gtI_PvR1T3MKbRszw10Owb9xxC2to',
    appId: '1:744760581508:web:cec01d20a42422f6f511d1',
    messagingSenderId: '744760581508',
    projectId: 'chat-app-2171',
    authDomain: 'chat-app-2171.firebaseapp.com',
    storageBucket: 'chat-app-2171.appspot.com',
    measurementId: 'G-XYXBS2F94S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvrDMNxSppUcGzwf-I8PwTRe7F8lw5R9s',
    appId: '1:744760581508:android:3cb0349797850506f511d1',
    messagingSenderId: '744760581508',
    projectId: 'chat-app-2171',
    storageBucket: 'chat-app-2171.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwGaQ3WNOiFObUYQ4M2WqABO66TtDCbs4',
    appId: '1:744760581508:ios:3cfde7bab1b647e5f511d1',
    messagingSenderId: '744760581508',
    projectId: 'chat-app-2171',
    storageBucket: 'chat-app-2171.appspot.com',
    iosClientId: '744760581508-pe3a5t23ogumru9abltq6h47a83ing0q.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwGaQ3WNOiFObUYQ4M2WqABO66TtDCbs4',
    appId: '1:744760581508:ios:3cfde7bab1b647e5f511d1',
    messagingSenderId: '744760581508',
    projectId: 'chat-app-2171',
    storageBucket: 'chat-app-2171.appspot.com',
    iosClientId: '744760581508-pe3a5t23ogumru9abltq6h47a83ing0q.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
